apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: clean-archit
  name: clean-archit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clean-archit
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clean-archit
    spec:
      containers:
      - image: 0758631838/clean-archi:latest
        imagePullPolicy: IfNotPresent
        name: clean-archi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-11-09T10:45:07Z"
  labels:
    app: clean-archit
  name: clean-archit
  namespace: default
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: clean-archit
  sessionAffinity: None
  type: LoadBalancer

