CREATE SCHEMA IF NOT EXISTS CLEAN_ARCHITECTURE;

SET SCHEMA CLEAN_ARCHITECTURE;
DROP TABLE IF EXISTS CLEAN_ARCHITECTURE.PERSONNE;

DROP SEQUENCE  IF EXISTS CLEAN_ARCHITECTURE.PERSONNE_ID_SEQ ;

/************************************************/
/* PERSONNE  */
/************************************************/

CREATE TABLE CLEAN_ARCHITECTURE.PERSONNE (
    ID            NUMBER          NOT NULL,
    NOM          VARCHAR2(10)    NOT NULL,
    PRENOM          VARCHAR2(100)   NOT NULL,
    AGE      NUMBER     NOT NULL,
    EMAIL   VARCHAR2(50)    NOT NULL
);

ALTER TABLE CLEAN_ARCHITECTURE.PERSONNE ADD CONSTRAINT PERSONNE_PK PRIMARY KEY (ID);

CREATE SEQUENCE CLEAN_ARCHITECTURE.PERSONNE_ID_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 10 NOCYCLE;

/************************************************/
/* POSITIONGPS  */
/************************************************/

CREATE TABLE CLEAN_ARCHITECTURE.POSITIONGPS (
    ID            NUMBER          NOT NULL,
    LATITUDE           VARCHAR2(100)     NOT NULL,
    LONGITUDE          VARCHAR2(100)   NOT NULL,
    MATRICULE      VARCHAR2(10)     NOT NULL,
    DATE_ENREG      TIMESTAMP           NOT NULL
 );

ALTER TABLE CLEAN_ARCHITECTURE.POSITIONGPS ADD CONSTRAINT POSITIONGPS_PK PRIMARY KEY (ID);

CREATE SEQUENCE CLEAN_ARCHITECTURE.POSITIONGPS_ID_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 10 NOCYCLE;



